import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
const mocks=vi.hoisted(()=>({user:vi.fn(),role:vi.fn(),create:vi.fn(),cookieSet:vi.fn(),cookieGet:vi.fn(),cookieDelete:vi.fn(),cookieAll:vi.fn()}));
vi.mock("next/headers",()=>({headers:async()=>new Headers(),cookies:async()=>({getAll:mocks.cookieAll,get:mocks.cookieGet,set:mocks.cookieSet,delete:mocks.cookieDelete})}));
vi.mock("@supabase/ssr",()=>({createServerClient:mocks.create}));
import { administrator, adminAuthClient, clearAdministratorCookies, setEnvironmentAdministratorCookie } from "@/lib/admin/server";
import { ADMIN_SESSION_COOKIE, ADMIN_SESSION_SECONDS, createEnvironmentAdminSession } from "@/lib/admin/environment-session";
beforeEach(()=>{vi.clearAllMocks();mocks.cookieGet.mockReturnValue(undefined);mocks.cookieAll.mockReturnValue([]);vi.stubEnv("NEXT_PUBLIC_SUPABASE_URL","https://example.supabase.co");vi.stubEnv("NEXT_PUBLIC_SUPABASE_ANON_KEY","anon");vi.stubEnv("SUPABASE_SERVICE_ROLE_KEY","server-only");vi.stubEnv("ADMIN_LOGIN_EMAIL","admin@example.com");vi.stubEnv("ADMIN_LOGIN_PASSWORD","");vi.stubEnv("NEXT_PUBLIC_APP_URL","https://app.example");vi.stubEnv("ADMIN_ENABLE_LOCAL_LOGIN","false");mocks.create.mockReturnValue({auth:{getUser:mocks.user},from:()=>({select:()=>({eq:()=>({eq:()=>({maybeSingle:mocks.role})})})})});mocks.user.mockResolvedValue({data:{user:{id:"admin",email:"admin@example.com"}},error:null});mocks.role.mockResolvedValue({data:{user_id:"admin"}});});
afterEach(()=>vi.unstubAllEnvs());
describe("server administrator authorization",()=>{
  it("allows only a provider-verified, enabled administrator",async()=>{expect(await administrator()).toEqual({id:"admin",email:"admin@example.com"});});
  it("denies a normal user even if a role response is present",async()=>{mocks.user.mockResolvedValue({data:{user:{id:"normal",email:"normal@example.com"}},error:null});expect(await administrator()).toBeNull();expect(mocks.role).not.toHaveBeenCalled();});
  it("denies disabled or removed administrator roles",async()=>{mocks.role.mockResolvedValue({data:null});expect(await administrator()).toBeNull();});
  it("fails closed on missing environment and invalid provider sessions",async()=>{vi.stubEnv("ADMIN_LOGIN_EMAIL","");expect(await administrator()).toBeNull();vi.stubEnv("ADMIN_LOGIN_EMAIL","admin@example.com");mocks.user.mockResolvedValue({data:{user:null},error:new Error("invalid")});expect(await administrator()).toBeNull();});
  it("uses a separate HTTP-only strict same-site cookie namespace",async()=>{await adminAuthClient();expect(mocks.create).toHaveBeenCalledWith(expect.any(String),"anon",expect.objectContaining({cookieOptions:expect.objectContaining({name:"outreach-admin-auth",httpOnly:true,sameSite:"strict"})}));});
  it("authorizes a signed environment session in production without a provider account",async()=>{vi.stubEnv("ADMIN_LOGIN_PASSWORD","test");vi.stubEnv("NODE_ENV","production");mocks.cookieGet.mockReturnValue({value:createEnvironmentAdminSession()});expect(await administrator()).toEqual({id:null,email:"admin@example.com"});expect(mocks.create).not.toHaveBeenCalled();});
  it("never accepts an old provider session when environment credentials are configured",async()=>{vi.stubEnv("ADMIN_LOGIN_PASSWORD","test");expect(await administrator()).toBeNull();expect(mocks.create).not.toHaveBeenCalled();mocks.cookieGet.mockReturnValue({value:"forged-cookie"});expect(await administrator()).toBeNull();});
  it("sets the environment cookie as HTTP-only, Secure, strict same-site and expiring",async()=>{vi.stubEnv("ADMIN_LOGIN_PASSWORD","test");vi.stubEnv("NODE_ENV","production");await setEnvironmentAdministratorCookie();expect(mocks.cookieSet).toHaveBeenCalledWith(ADMIN_SESSION_COOKIE,expect.any(String),{httpOnly:true,secure:true,sameSite:"strict",path:"/",maxAge:ADMIN_SESSION_SECONDS});});
  it("clears every admin cookie but preserves the ordinary workspace session",async()=>{mocks.cookieAll.mockReturnValue([{name:ADMIN_SESSION_COOKIE},{name:"outreach-admin-auth"},{name:"outreach-local-admin"},{name:"sb-workspace-auth-token"}]);await clearAdministratorCookies();expect(mocks.cookieDelete.mock.calls).toEqual([[ADMIN_SESSION_COOKIE],["outreach-admin-auth"],["outreach-local-admin"]]);});
});
