import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
const mocks=vi.hoisted(()=>({admin:vi.fn(),database:vi.fn(),rpc:vi.fn(),origin:vi.fn(),limit:vi.fn(),signIn:vi.fn(),audit:vi.fn(),setSession:vi.fn(),clear:vi.fn()}));
vi.mock("@/lib/admin/server",()=>({administrator:mocks.admin,privilegedDatabase:mocks.database,assertSameOrigin:mocks.origin,clearAdministratorCookies:mocks.clear,setEnvironmentAdministratorCookie:mocks.setSession,limitRequest:mocks.limit,adminAuthClient:async()=>({auth:{signInWithPassword:mocks.signIn,signOut:vi.fn()}})}));
vi.mock("next/headers",()=>({cookies:async()=>({set:vi.fn(),delete:vi.fn()})}));
import { POST as settings } from "@/app/api/admin/microsoft/route";
import { POST as login } from "@/app/api/admin/login/route";

const input={name:"Company",client_id:"22222222-2222-4222-8222-222222222222",tenant_id:"33333333-3333-4333-8333-333333333333",enabled:true,allow_custom:true,fallback_audience:"AzureADandPersonalMicrosoftAccount"};
const request=(body:unknown)=>new Request("https://app.example/api/admin",{method:"POST",headers:{Origin:"https://app.example","Content-Type":"application/json"},body:JSON.stringify(body)});
beforeEach(()=>{vi.clearAllMocks();mocks.origin.mockImplementation(()=>undefined);mocks.limit.mockResolvedValue(undefined);mocks.admin.mockResolvedValue({id:"admin",email:"admin@example.com"});mocks.rpc.mockResolvedValue({error:null});mocks.audit.mockResolvedValue({error:null});mocks.database.mockReturnValue({rpc:mocks.rpc,from:()=>({select:()=>({maybeSingle:async()=>({data:input,error:null})}),insert:mocks.audit})});vi.stubEnv("ADMIN_LOGIN_EMAIL","admin@example.com");vi.stubEnv("ADMIN_LOGIN_PASSWORD","");vi.stubEnv("SUPABASE_SERVICE_ROLE_KEY","server-test-fixture");vi.stubEnv("NEXT_PUBLIC_APP_URL","https://app.example");vi.stubEnv("NODE_ENV","production");vi.stubEnv("ADMIN_ENABLE_LOCAL_LOGIN","true");});
afterEach(()=>vi.unstubAllEnvs());
describe("protected administrator endpoints",()=>{
  it("rejects normal users before using privileged data",async()=>{mocks.admin.mockResolvedValue(null);expect((await settings(request(input))).status).toBe(403);expect(mocks.database).not.toHaveBeenCalled();});
  it("saves settings and audit identity through the transactional RPC",async()=>{expect((await settings(request(input))).status).toBe(200);expect(mocks.rpc).toHaveBeenCalledWith("save_microsoft_default",{p_settings:input,p_actor:"admin",p_email:"admin@example.com"});});
  it("rejects malformed identifiers before persistence",async()=>{expect((await settings(request({...input,client_id:"not-a-client"}))).status).toBe(400);expect(mocks.rpc).not.toHaveBeenCalled();});
  it("rejects cross-origin writes",async()=>{mocks.origin.mockImplementation(()=>{throw new Error("Wrong Origin");});expect((await settings(request(input))).status).toBe(400);expect(mocks.database).not.toHaveBeenCalled();});
  it("passes an existing short production password to the provider instead of rejecting its length",async()=>{mocks.signIn.mockResolvedValue({error:null});expect((await login(request({email:"admin@example.com",password:"test"}))).status).toBe(200);expect(mocks.signIn).toHaveBeenCalledWith({email:"admin@example.com",password:"test"});});
  it("does not accept a local hash as production authentication",async()=>{mocks.signIn.mockResolvedValue({error:new Error("Invalid credentials")});expect((await login(request({email:"admin@example.com",password:"test"}))).status).toBe(401);});
  it("denies administrator access even with valid provider credentials if the role check fails",async()=>{mocks.signIn.mockResolvedValue({error:null});mocks.admin.mockResolvedValue(null);expect((await login(request({email:"admin@example.com",password:"test"}))).status).toBe(401);});
  it("requires provider authentication even when obsolete loopback-test flags are set",async()=>{vi.stubEnv("NODE_ENV","development");vi.stubEnv("VERCEL","");vi.stubEnv("ADMIN_LOCAL_SESSION_SECRET","legacy-secret");vi.stubEnv("ADMIN_DEV_PASSWORD_HASH","legacy-hash");mocks.signIn.mockResolvedValue({error:new Error("Invalid credentials")});const response=await login(new Request("http://127.0.0.1:3000/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:"admin@example.com",password:"test"})}));expect(response.status).toBe(401);expect(mocks.signIn).toHaveBeenCalledWith({email:"admin@example.com",password:"test"});});
  it("uses secure provider credentials for production login",async()=>{mocks.signIn.mockResolvedValue({error:null});expect((await login(request({email:"admin@example.com",password:"Strong-example-Password-7!"}))).status).toBe(200);expect(mocks.signIn).toHaveBeenCalledWith({email:"admin@example.com",password:"Strong-example-Password-7!"});});
  it("accepts the environment password in production without a Supabase admin signup",async()=>{vi.stubEnv("ADMIN_LOGIN_PASSWORD","test");vi.stubEnv("VERCEL","1");expect((await login(request({email:"ADMIN@example.com",password:"test"}))).status).toBe(200);expect(mocks.signIn).not.toHaveBeenCalled();expect(mocks.setSession).toHaveBeenCalledOnce();expect(mocks.audit).toHaveBeenCalledWith({actor_email:"admin@example.com",action:"admin_login_success",details:{}});});
  it("does not fall back to the provider when the environment password is incorrect",async()=>{vi.stubEnv("ADMIN_LOGIN_PASSWORD","test");mocks.signIn.mockResolvedValue({error:null});expect((await login(request({email:"admin@example.com",password:"wrong"}))).status).toBe(401);expect(mocks.signIn).not.toHaveBeenCalled();expect(mocks.setSession).not.toHaveBeenCalled();expect(mocks.clear).toHaveBeenCalled();});
  it("rejects the correct environment password with the wrong email",async()=>{vi.stubEnv("ADMIN_LOGIN_PASSWORD","test");expect((await login(request({email:"user@example.com",password:"test"}))).status).toBe(401);expect(mocks.setSession).not.toHaveBeenCalled();});
  it("issues no environment session when audit persistence fails",async()=>{vi.stubEnv("ADMIN_LOGIN_PASSWORD","test");mocks.audit.mockResolvedValue({error:new Error("Database unavailable")});expect((await login(request({email:"admin@example.com",password:"test"}))).status).toBe(400);expect(mocks.setSession).not.toHaveBeenCalled();expect(mocks.clear).toHaveBeenCalled();});
  it("fails closed before environment authentication when rate limiting is unavailable",async()=>{vi.stubEnv("ADMIN_LOGIN_PASSWORD","test");mocks.limit.mockRejectedValueOnce(new Error("Security checks are unavailable"));expect((await login(request({email:"admin@example.com",password:"test"}))).status).toBe(400);expect(mocks.setSession).not.toHaveBeenCalled();expect(mocks.audit).not.toHaveBeenCalled();});
  it("saves environment administrator settings with a nullable audit actor",async()=>{mocks.admin.mockResolvedValue({id:null,email:"admin@example.com"});expect((await settings(request(input))).status).toBe(200);expect(mocks.rpc).toHaveBeenCalledWith("save_microsoft_default",{p_settings:input,p_actor:null,p_email:"admin@example.com"});});
});
