// @vitest-environment node
import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
const sql=readFileSync("supabase/migrations/20261009_admin_controls.sql","utf8");
describe("account-controls migration contract (not a live RLS test)",()=>{
  it("is additive and never deletes Auth or Storage metadata using SQL",()=>{expect(sql).toContain("begin;");expect(sql).toContain("commit;");expect(sql).not.toMatch(/delete from (auth\.users|storage\.objects)|drop table|truncate/i);});
  it("restricts directory and account mutations to the service role",()=>{expect(sql).toContain("admin_user_directory(text,text,integer) from public, anon, authenticated");expect(sql).toContain("admin_user_directory(text,text,integer) to service_role");expect(sql).toContain("public.admin_disconnect_sender(uuid,uuid,text) from public, anon, authenticated");expect(sql).toContain("public.admin_disconnect_sender(uuid,uuid,text) to service_role");});
  it("retains deletion state independently of Auth and freezes existing JWT access",()=>{expect(sql).toContain("user_id uuid primary key, -- intentionally retained");expect(sql).toContain("as restrictive for all to authenticated");expect(sql).toContain("on storage.objects as restrictive");expect(sql).toContain("public.workspace_access_allowed()");expect(sql).toContain("'email_history'");expect(sql).toContain("'dataset_rows'");});
  it("protects administrators, requires confirmation, serializes cleanup and audits changes",()=>{expect(sql).toContain("p_target = p_actor");expect(sql).toContain("lower(target_email) = lower(p_email)");expect(sql).toContain("where user_id = p_target and enabled");expect(sql).toContain("lower(trim(p_confirmation)) <> lower(target_email)");expect(sql).toContain("pg_advisory_xact_lock");expect(sql).toContain("existing.lease_until > now()");expect(sql).toContain("where user_id = p_target and lease_id = p_lease");for(const action of ["account_deletion_started","account_deleted","account_deletion_failed","sender_disconnected"])expect(sql).toContain(action);});
  it("includes profile-less accounts and interrupted post-Auth cleanup in the directory",()=>{expect(sql).toContain("from auth.users");expect(sql).toContain("left join public.profiles");expect(sql).toContain("union all");expect(sql).toContain("d.status <> 'deleted'");expect(sql).toContain("confirmation_email = case when p_complete then null");});
  it("does not prevent default sender resets or cascading SET NULL updates",()=>{expect(sql).toContain("array['profiles','microsoft_integrations','microsoft_user_configurations']");expect(sql).toContain("to_jsonb(new)->>'connection_status' = 'not_connected'");});
});
