import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
const mocks=vi.hoisted(()=>({database:vi.fn(),filters:[] as Array<[string,unknown]>,foreign:false,hasIntegration:true,noAudience:false,savedAuthority:null as string|null}));
vi.mock("@/lib/admin/server",()=>({privilegedDatabase:mocks.database}));
import { configurationForUser } from "@/lib/microsoft/configuration-server";
const id="11111111-1111-4111-8111-111111111111",client="22222222-2222-4222-8222-222222222222",tenant="33333333-3333-4333-8333-333333333333";
beforeEach(()=>{mocks.filters=[];mocks.foreign=false;mocks.hasIntegration=true;mocks.noAudience=false;mocks.savedAuthority=null;vi.stubEnv("MICROSOFT_READER_TENANT_ID","");mocks.database.mockReturnValue({from:(table:string)=>{const query={select:()=>query,eq:(key:string,value:unknown)=>{mocks.filters.push([key,value]);return query;},maybeSingle:async()=>({error:null,data:table==="microsoft_integrations"?(mocks.hasIntegration?{configuration_id:id,connection_method:"custom",resolved_authority:mocks.savedAuthority}:null):table==="microsoft_default_configuration"?{id,enabled:true,allow_custom:true,client_id:client,tenant_id:tenant,fallback_audience:mocks.noAudience?null:"AzureADandPersonalMicrosoftAccount",validated_at:new Date().toISOString()}:mocks.foreign?null:{id,client_id:client,tenant_id:tenant,fallback_audience:mocks.noAudience?null:"PersonalMicrosoftAccount",validated_at:new Date().toISOString(),detected_audience:null}})};return query;}});});
afterEach(()=>vi.unstubAllEnvs());
describe("configuration ownership and honest fallbacks",()=>{
  it("allows default sign-in with IDs only and does not fabricate a verified audience",async()=>{mocks.noAudience=true;mocks.hasIntegration=false;const result=await configurationForUser("owner-a");expect(result.authority).toBe("https://login.microsoftonline.com/common");expect(result.audience).toBeNull();expect(result.detected_audience).toBeUndefined();expect(result.verification).toBe("unverified");});
  it("allows an IDs-only private registration without mandatory account-type selection",async()=>{mocks.noAudience=true;const result=await configurationForUser("owner-a");expect(result.method).toBe("custom");expect(result.authority).toBe("https://login.microsoftonline.com/common");expect(result.verification).toBe("unverified");});
  it("resolves the configured tenant for a single-tenant retry without claiming detection",async()=>{mocks.noAudience=true;const result=await configurationForUser("owner-a",{signInEndpoint:"tenant"});expect(result.authority).toBe(`https://login.microsoftonline.com/${tenant}`);expect(result.audience).toBeNull();expect(result.verification).toBe("unverified");});
  it("keeps a learned tenant endpoint confined to the owner’s active registration",async()=>{mocks.noAudience=true;mocks.savedAuthority=`https://login.microsoftonline.com/${tenant}`;expect((await configurationForUser("owner-a")).authority).toBe(mocks.savedAuthority);expect((await configurationForUser("owner-a",{method:"default"})).authority).toBe("https://login.microsoftonline.com/common");});
  it("does not override known account restrictions with an automatic tenant retry",async()=>{expect((await configurationForUser("owner-a",{signInEndpoint:"tenant"})).authority).toBe("https://login.microsoftonline.com/consumers");});
  it("inherits enabled administrator defaults when no configuration has been saved",async()=>{mocks.hasIntegration=false;const result=await configurationForUser("new-owner");expect(result.method).toBe("default");expect(result.home_account_id).toBeNull();expect(result.connected_email).toBeNull();});
  it("looks up a personal configuration using both owner and ID",async()=>{const result=await configurationForUser("owner-a");expect(mocks.filters).toContainEqual(["user_id","owner-a"]);expect(mocks.filters).toContainEqual(["id",id]);expect(result.authority).toBe("https://login.microsoftonline.com/consumers");expect(result.verification).toBe("manual");});
  it("denies missing/foreign personal configurations",async()=>{mocks.foreign=true;await expect(configurationForUser("owner-a",{id})).rejects.toThrow("not available to your account");});
  it("selects centrally controlled default configuration without treating it as personal ownership",async()=>{const result=await configurationForUser("owner-a",{method:"default"});expect(result.method).toBe("default");expect(result.authority).toBe("https://login.microsoftonline.com/common");expect(result.verification).toBe("manual");});
});
