import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
vi.mock("@/lib/admin/server",()=>({privilegedDatabase:vi.fn()}));
import { detectConfiguration } from "@/lib/microsoft/configuration-server";
import type { MicrosoftConfiguration } from "@/lib/microsoft/authority";
const configuration:MicrosoftConfiguration={id:"11111111-1111-4111-8111-111111111111",client_id:"22222222-2222-4222-8222-222222222222",tenant_id:"33333333-3333-4333-8333-333333333333",name:"Company",fallback_audience:null,detected_audience:null,verified_at:null,validation_error:null,updated_at:new Date().toISOString()};
beforeEach(()=>{vi.stubEnv("MICROSOFT_READER_TENANT_ID",configuration.tenant_id);vi.stubEnv("MICROSOFT_READER_CLIENT_ID","reader");vi.stubEnv("MICROSOFT_READER_CLIENT_SECRET","test-reader-credential");vi.stubEnv("MICROSOFT_READABLE_APP_IDS",configuration.client_id);});
afterEach(()=>{vi.unstubAllGlobals();vi.unstubAllEnvs();});
describe("authorized audience detection",()=>{
  it("reads metadata through fixed backend endpoints and does not return credentials",async()=>{const fetcher=vi.fn().mockResolvedValueOnce(Response.json({access_token:"backend-only-token"})).mockResolvedValueOnce(Response.json({signInAudience:"AzureADandPersonalMicrosoftAccount"}));vi.stubGlobal("fetch",fetcher);const result=await detectConfiguration(configuration,true);expect(result.detected_audience).toBe("AzureADandPersonalMicrosoftAccount");expect(result.verified_at).toBeTruthy();expect(JSON.stringify(result)).not.toContain("backend-only-token");expect(fetcher.mock.calls[1][0]).toContain("/applications(appId='22222222-2222-4222-8222-222222222222')?$select=signInAudience");});
  it("never uses privileged credentials against another tenant",async()=>{const fetcher=vi.fn();vi.stubGlobal("fetch",fetcher);const result=await detectConfiguration({...configuration,tenant_id:"44444444-4444-4444-8444-444444444444"},true);expect(fetcher).not.toHaveBeenCalled();expect(result.detected_audience).toBeNull();expect(result.validation_error).toContain("unavailable");});
  it("does not inspect registrations absent from the operator allowlist",async()=>{const fetcher=vi.fn();vi.stubGlobal("fetch",fetcher);vi.stubEnv("MICROSOFT_READABLE_APP_IDS","");expect((await detectConfiguration(configuration,true)).verified_at).toBeNull();expect(fetcher).not.toHaveBeenCalled();});
  it("honestly handles missing consent and does not retain stale verified metadata",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValueOnce(Response.json({access_token:"token"})).mockResolvedValueOnce(new Response(null,{status:403})));const result=await detectConfiguration({...configuration,detected_audience:"AzureADMyOrg",verified_at:"2020-01-01"},true);expect(result.detected_audience).toBeNull();expect(result.verified_at).toBeNull();expect(result.validation_error).toContain("Application.Read.All");});
  it("caches briefly but forced refresh sees remote audience changes",async()=>{const fetcher=vi.fn().mockResolvedValueOnce(Response.json({access_token:"token"})).mockResolvedValueOnce(Response.json({signInAudience:"PersonalMicrosoftAccount"}));vi.stubGlobal("fetch",fetcher);const cached={...configuration,detected_audience:"AzureADMyOrg" as const,verified_at:new Date().toISOString(),validated_at:new Date().toISOString()};expect((await detectConfiguration(cached)).detected_audience).toBe("AzureADMyOrg");expect(fetcher).not.toHaveBeenCalled();expect((await detectConfiguration(cached,true)).detected_audience).toBe("PersonalMicrosoftAccount");});
});
