import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
const mocks=vi.hoisted(()=>({user:vi.fn(),database:vi.fn(),configuration:vi.fn(),mutations:[] as Array<{table:string;kind:string;value:unknown}>,filters:[] as Array<[string,string,unknown]>}));
vi.mock("@/lib/supabase/server",()=>({getSupabaseServerClient:async()=>({auth:{getUser:mocks.user}})}));
vi.mock("@/lib/admin/server",()=>({privilegedDatabase:mocks.database,assertSameOrigin:vi.fn(),limitRequest:vi.fn()}));
vi.mock("@/lib/microsoft/configuration-server",()=>({configurationForUser:mocks.configuration,ConfigurationNeedsFallback:class extends Error{}}));
import { GET, POST } from "@/app/api/microsoft/configuration/route";
const id="11111111-1111-4111-8111-111111111111",client="22222222-2222-4222-8222-222222222222",tenant="33333333-3333-4333-8333-333333333333";
function request(body:unknown){return new Request("https://app.example/api/microsoft/configuration",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});}
beforeEach(()=>{vi.clearAllMocks();mocks.mutations=[];mocks.filters=[];mocks.user.mockResolvedValue({data:{user:{id:"actual-owner"}},error:null});mocks.configuration.mockResolvedValue({id,client_id:client,tenant_id:tenant,method:"custom",authority:"https://login.microsoftonline.com/common",home_account_id:"selected-home",connected_email:"sender@example.com"});mocks.database.mockReturnValue({from:(table:string)=>{const query={select:()=>query,eq:(key:string,value:unknown)=>{mocks.filters.push([table,key,value]);return query;},upsert:(value:unknown)=>{mocks.mutations.push({table,kind:"upsert",value});return query;},delete:()=>{mocks.mutations.push({table,kind:"delete",value:null});return query;},update:(value:unknown)=>{mocks.mutations.push({table,kind:"update",value});return query;},maybeSingle:async()=>({data:null,error:null}),single:async()=>({data:{id,client_id:client,tenant_id:tenant,user_id:"actual-owner"},error:null}),then:(resolve:(value:unknown)=>unknown)=>Promise.resolve({error:null}).then(resolve)};return query;}});vi.stubGlobal("fetch",vi.fn());});
afterEach(()=>vi.unstubAllGlobals());
describe("owner-scoped Microsoft API",()=>{
  it("restricts automatic retry to the configured tenant rather than accepting arbitrary authorities",async()=>{expect((await POST(request({action:"select",method:"custom",id,signInEndpoint:"https://evil.example"}))).status).toBe(400);expect(mocks.configuration).not.toHaveBeenCalled();expect(mocks.mutations).toEqual([]);});
  it("persists the selected automatic authority with the authenticated owner's disconnected sender",async()=>{expect((await POST(request({action:"select",method:"custom",id,signInEndpoint:"tenant",user_id:"victim"}))).status).toBe(200);expect(mocks.configuration).toHaveBeenCalledWith("actual-owner",expect.objectContaining({method:"custom",id,signInEndpoint:"tenant",force:true}));expect(mocks.mutations).toContainEqual(expect.objectContaining({value:expect.objectContaining({user_id:"actual-owner",connection_status:"not_connected",home_account_id:null,resolved_authority:"https://login.microsoftonline.com/common"})}));});
  it("uses the authenticated owner rather than a supplied user ID when saving",async()=>{const response=await POST(request({action:"save",user_id:"victim",client_id:client,tenant_id:tenant,name:"My app"}));expect(response.status).toBe(200);expect(mocks.mutations[0]).toEqual(expect.objectContaining({table:"microsoft_user_configurations",value:expect.objectContaining({user_id:"actual-owner"})}));expect(mocks.mutations.some((item)=>item.table==="microsoft_default_configuration")).toBe(false);});
  it("filters deletion and sender reset by the authenticated owner",async()=>{expect((await POST(request({action:"remove",id}))).status).toBe(200);expect(mocks.filters).toContainEqual(["microsoft_user_configurations","user_id","actual-owner"]);expect(mocks.filters).toContainEqual(["microsoft_integrations","user_id","actual-owner"]);});
  it("rejects wrong-account verification before calling Graph or saving metadata",async()=>{const response=await POST(request({action:"verify",accessToken:"test-token",homeAccountId:"wrong-home",authority:"https://login.microsoftonline.com/common",configurationId:id,clientId:client}));expect(response.status).toBe(400);expect(fetch).not.toHaveBeenCalled();expect(mocks.mutations).toEqual([]);});
  it("clears obsolete expected-email restrictions when choosing a configuration",async()=>{expect((await POST(request({action:"select",method:"custom",id,expected_email:"old@example.com"}))).status).toBe(200);expect(mocks.mutations).toContainEqual(expect.objectContaining({value:expect.objectContaining({user_id:"actual-owner",expected_email:null,connection_status:"not_connected"})}));});
  it("does not allow the removed sender-rule action to restore restrictions",async()=>{expect((await POST(request({action:"sender-rule",expected_email:"old@example.com"}))).status).toBe(400);expect(mocks.mutations).toEqual([]);});
  it("connects the chosen Microsoft mailbox without a manually entered expected address",async()=>{vi.mocked(fetch).mockResolvedValue(Response.json({mail:"new-sender@example.com",displayName:"New Sender"}));const response=await POST(request({action:"connect",accessToken:"test-token",homeAccountId:"new-home",authority:"https://login.microsoftonline.com/common",configurationId:id,clientId:client,expected_email:"old@example.com"}));expect(response.status).toBe(200);expect(mocks.mutations).toContainEqual(expect.objectContaining({value:expect.objectContaining({user_id:"actual-owner",expected_email:null,connected_email:"new-sender@example.com",home_account_id:"new-home",connection_status:"connected"})}));});
  it("rejects unauthenticated reads before privileged configuration access",async()=>{mocks.user.mockResolvedValue({data:{user:null},error:null});expect((await GET(new Request("https://app.example/api/microsoft/configuration"))).status).toBe(400);expect(mocks.configuration).not.toHaveBeenCalled();expect(mocks.database).not.toHaveBeenCalled();});
});
