"use client";

import { useState } from "react";
import { ExternalLink, LoaderCircle, PlugZap, Unplug } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";
import { acquireGraphToken, connectMicrosoft, disconnectMicrosoft } from "@/lib/microsoft/msal";
import type { MicrosoftIntegration } from "@/types";

export function MicrosoftSettings({ integration }: { integration?: Partial<MicrosoftIntegration> | null }) {
  const [tenantId, setTenantId] = useState(integration?.tenant_id ?? ""); const [clientId, setClientId] = useState(integration?.client_id ?? ""); const [expectedEmail, setExpectedEmail] = useState(integration?.expected_email ?? "");
  const [status, setStatus] = useState(integration?.connection_status ?? "not_connected"); const [connectedEmail, setConnectedEmail] = useState(integration?.connected_email ?? ""); const [pending, setPending] = useState("");
  async function save(patch: Record<string, unknown> = {}) { const supabase = getSupabaseBrowserClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) throw new Error("Sign in again."); const { error } = await supabase.from("microsoft_integrations").upsert({ user_id: user.id, tenant_id: tenantId.trim(), client_id: clientId.trim(), expected_email: expectedEmail.trim() || null, ...patch }, { onConflict: "user_id" }); if (error) throw error; }
  async function saveConfig() { setPending("save"); try { await save(); toast.success("Microsoft configuration saved."); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not save."); } finally { setPending(""); } }
  async function connect() { if (!tenantId || !clientId) return toast.error("Save a Tenant ID and Client ID first."); setPending("connect"); try { await save(); const account = await connectMicrosoft(tenantId, clientId); const email = account.username; if (expectedEmail && email.toLowerCase() !== expectedEmail.trim().toLowerCase()) throw new Error(`Connected account ${email} does not match the expected Microsoft email.`); await save({ connected_email: email, connection_status: "connected", last_connected_at: new Date().toISOString(), last_error: null }); setConnectedEmail(email); setStatus("connected"); toast.success("Microsoft account connected."); } catch (error) { await save({ connection_status: "error", last_error: error instanceof Error ? error.message : "Connection failed" }).catch(() => undefined); setStatus("error"); toast.error(error instanceof Error ? error.message : "Microsoft connection failed."); } finally { setPending(""); } }
  async function test() { setPending("test"); try { const { token } = await acquireGraphToken(tenantId, clientId); const response = await fetch("https://graph.microsoft.com/v1.0/me?$select=displayName,mail,userPrincipalName", { headers: { Authorization: `Bearer ${token}` } }); if (!response.ok) throw new Error("Microsoft connection test failed."); const profile = await response.json() as { mail?: string; userPrincipalName?: string }; const email = profile.mail || profile.userPrincipalName || connectedEmail; await save({ connected_email: email, connection_status: "connected", last_connected_at: new Date().toISOString(), last_error: null }); setConnectedEmail(email); setStatus("connected"); toast.success("Connection and User.Read permission verified. No email was sent."); } catch (error) { toast.error(error instanceof Error ? error.message : "Connection test failed."); } finally { setPending(""); } }
  async function disconnect() { setPending("disconnect"); try { await disconnectMicrosoft(tenantId, clientId); await save({ connected_email: null, connection_status: "not_connected", last_error: null }); setConnectedEmail(""); setStatus("not_connected"); toast.success("Microsoft account disconnected."); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not disconnect."); } finally { setPending(""); } }
  return <Card id="microsoft"><CardHeader className="flex flex-row items-center justify-between"><div><CardTitle>Microsoft 365</CardTitle><p className="mt-1 text-sm text-[#68736f]">Your own Entra SPA configuration. No client secret or Microsoft password is stored.</p></div><Badge tone={status === "connected" ? "success" : status === "error" ? "danger" : "warning"}>{status.replaceAll("_", " ")}</Badge></CardHeader><CardContent><div className="grid gap-4 md:grid-cols-2"><div><Label>Tenant ID</Label><Input value={tenantId} onChange={(e) => setTenantId(e.target.value)} placeholder="Directory (tenant) ID" /></div><div><Label>Application / Client ID</Label><Input value={clientId} onChange={(e) => setClientId(e.target.value)} placeholder="Application (client) ID" /></div><div className="md:col-span-2"><Label>Expected Microsoft email</Label><Input type="email" value={expectedEmail} onChange={(e) => setExpectedEmail(e.target.value)} placeholder="you@organization.com" /></div></div>{connectedEmail && <div className="mt-4 rounded-lg bg-[#edf7f2] px-4 py-3 text-sm text-[#176b55]">Connected as <strong>{connectedEmail}</strong></div>}<div className="mt-5 flex flex-wrap gap-2"><Button variant="outline" onClick={saveConfig} disabled={Boolean(pending)}>{pending === "save" && <LoaderCircle className="animate-spin" size={14} />}Save configuration</Button><Button onClick={connect} disabled={Boolean(pending)}><PlugZap size={15} />Connect account</Button><Button variant="outline" onClick={test} disabled={Boolean(pending) || status !== "connected"}>Test connection</Button><Button variant="ghost" onClick={disconnect} disabled={Boolean(pending) || status === "not_connected"}><Unplug size={15} />Disconnect</Button><a href="https://entra.microsoft.com/" target="_blank" rel="noreferrer"><Button variant="ghost">Open Entra <ExternalLink size={14} /></Button></a></div></CardContent></Card>;
}
