export const guideTopics = { "microsoft-setup": "Microsoft Entra setup", "default-connection": "Connect using the default configuration", "custom-connection": "Connect using your own app registration", permissions: "Microsoft permissions explained", troubleshooting: "Microsoft connection troubleshooting" } as const;
export const glossary = [
  ["Microsoft Entra ID","Microsoft's identity service for organizations: it controls access to their applications. Personal Microsoft accounts are not automatically members of a company directory."],
  ["App registration","A Microsoft record identifying the website that asks for sign-in and email permissions. Registration alone grants no mailbox access."],
  ["Client ID","The public identifier of the registration. It identifies the app, not the sender, and is not a password."],
  ["Tenant ID","The identifier of the directory owning the registration. Copy it from Overview. Personal-account sign-in does not imply every personal account has a conventional organizational tenant."],
  ["Microsoft Graph","Microsoft's API, used here to identify the signed-in account and request sending an email."],
  ["Redirect URI","The exact approved website address Microsoft returns to after login, including protocol, domain, port, and path."],
  ["API permissions","Actions an app may request, such as reading your basic profile or sending mail."],
  ["Delegated permissions","Access on behalf of the person who signs in. AUTMAIL sends from that person's mailbox, not automatically the app owner's mailbox."],
  ["Consent","Approval to use requested permissions. Organization policy may require an administrator to approve."],
  ["Access token","A short-lived credential Microsoft issues after sign-in and consent. Do not share it. AUTMAIL does not save access or refresh tokens in its database."],
];
export const registrationSteps = [
  "Open https://entra.microsoft.com. Sign in with an account authorized to manage app registrations. Your organization may require administrator assistance.",
  "Find Microsoft Entra ID → App registrations → New registration. Enter a recognizable name.",
  "Choose Supported account types using the four explanations below. Choose who will sign in—not who receives emails.",
  "Click Register. Copy Application (client) ID and Directory (tenant) ID from Overview. Use the directory owning this registration, not a guessed company directory. Personal accounts may need an existing permitted registration/registration owner rather than having an organizational directory themselves.",
  "Open Authentication → Add a platform → Single-page application. Register the exact Settings URL shown below. Do not use the Web platform or create a client secret for normal delegated login.",
  "Open API permissions → Add a permission → Microsoft Graph → Delegated permissions. Search for and add User.Read and Mail.Send. Review your organization's consent rules.",
  "For personal-account audiences, the registration's api.requestedAccessTokenVersion must be compatible: personal-account audiences require version 2. If Entra reports a token-version error, ask the registration owner to review the manifest using Microsoft's documentation.",
  "In AUTMAIL, open Settings → Email account → Use My Own Configuration. Name the configuration, paste the IDs, save, and validate.",
  "Click Connect account after saving. Optional metadata detection is not required. Automatic sign-in starts at Microsoft's general endpoint and retries the configured tenant only for an explicit single-tenant endpoint error. Account-type overrides are optional advanced settings, not verified detection.",
  "Click Connect account, choose the mailbox that should send, and grant consent. Run Test connection: it verifies basic Graph access without sending email.",
];
export const accountTypes = [
  ["One organization / AzureADMyOrg","Employees and permitted guests of one organization; authority uses its tenant ID."],
  ["Multiple organizations / AzureADMultipleOrgs","Work/school accounts across Microsoft Entra organizations; authority uses /organizations."],
  ["Organizations and personal / AzureADandPersonalMicrosoftAccount","Work/school and personal Outlook/Hotmail/Microsoft accounts; authority uses /common."],
  ["Personal only / PersonalMicrosoftAccount","Personal Microsoft accounts, not organizational-only accounts; authority uses /consumers."],
];
// Each item provides What happened, Why, Fix, and Verification, without promising tenant policy bypasses.
export const troubleshooting = [
  ["AADSTS50020 / wrong tenant","Microsoft rejected this account for the chosen tenant/app.","Authority, audience, directory membership, or guest invitation may not match.","Check the selected account and registration's Supported account types. For single tenant, use a permitted member/guest or ask its owner about invitations. Personal accounts require a genuinely supported audience; changing a URL does not change the registration.","Refresh configuration, reconnect, and check the saved sender. Run Test connection."],
  ["Single-tenant, multitenant, or personal-account mismatch","An account outside the configured audience cannot sign in.","The registration and login authority may support different account types.","Check Entra. Refresh verified metadata or correct the clearly labeled manual fallback. Single tenant uses its tenant ID; multiple organizations uses organizations; both account types uses common; personal-only uses consumers.","Confirm audience and authority, then reconnect the intended sender."],
  ["Redirect URI mismatch / AADSTS50011","Microsoft rejected the return address.","The exact Settings URL is not registered as a Single-page application redirect.","Copy the URL below into Authentication → Single-page application. Match HTTPS, domain, localhost port, and /settings exactly. /auth/callback belongs to Supabase, not this Microsoft popup.","Save in Entra and reconnect. Do not add unused callback URLs."],
  ["Invalid Client ID, Tenant ID, or application not found","The requested registration/directory cannot be located.","A typo, Object ID mistaken for Client ID, or wrong owning directory may be involved.","Copy Application (client) ID and Directory (tenant) ID from the same registration Overview. Use UUID values. The optional reader inspects only explicitly allowlisted apps in its own directory.","Save and validate the corrected IDs."],
  ["Missing Mail.Send permission","Email sending cannot be authorized.","Delegated Mail.Send may not be configured, consented, or allowed by policy.","The registration owner adds Graph delegated Mail.Send. Reconnect to request consent; your organization may require administrator approval. IDs alone grant no permission.","Reconnect, then use a separately confirmed test email if actual sending acceptance needs testing."],
  ["Administrator approval required / consent denied","Microsoft stopped permission approval.","The user declined, or organizational policy prevents user approval.","Ask the Microsoft administrator to review the app and delegated permissions. Do not request directory-wide reading permission from ordinary outreach users as a workaround.","After approval, reconnect and Test connection."],
  ["Unsupported account type","The selected Microsoft account is not admitted.","The app may be organizational-only or personal-only, or your fallback may be incorrect.","Use a supported account or ask the app owner to change its supported audience. If metadata cannot be read, update the manual fallback only after checking Entra.","Refresh and reconnect. Check the verification label; successful login is not proof of signInAudience detection."],
  ["Popup blocked","The Microsoft window did not open.","Browser popup rules or another pending interaction may block it.","Allow popups for this website, close other sign-in windows, then click Connect again.","The popup completes and the saved sender is the intended account."],
  ["Expired token / Graph 401","Microsoft rejected authentication.","The token may be expired, invalid, or revoked.","Reconnect in Settings. Silent renewal is attempted first; interactive renewal occurs only when MSAL reports interaction is required.","Test connection succeeds for the selected sender; do not retry uncertain emails blindly."],
  ["Graph 403","Microsoft denied this operation.","Consent, mailbox rights, license restrictions, or tenant policy may apply.","Ask the administrator to check delegated permissions and mailbox provisioning. Not every 403 has the same cause; do not bypass organizational controls.","Verify /me access, then a separately confirmed test email if sending must be tested."],
  ["Graph 429 / rate limits","Microsoft asked the app to slow down.","The workload was throttled.","Pause the batch, honor Retry-After, and reduce sending speed. Only explicit throttling responses are retried; uncertain POSTs are not blindly repeated.","Resume after throttling clears and verify the review still shows the intended sender."],
  ["Mailbox unavailable / sending restrictions","Sign-in may work while sending fails.","The account may lack a provisioned Exchange/Outlook mailbox, licensing, or permitted sending access.","Ask the mailbox administrator to verify provisioning, licensing, and sending policies. Sign-in does not create a mailbox. Arbitrary From addresses and Exchange delegation are not configured by this tracker.","Check the mailbox and a separately confirmed test email; acceptance still does not prove delivery."],
  ["requestedAccessTokenVersion errors","Entra rejected token configuration.","The manifest version may be incompatible with the audience.","Ask the registration owner to check api.requestedAccessTokenVersion and Supported account types. Personal-account audiences require version 2. Do not change unrelated manifest settings blindly.","Save compatible Entra settings, refresh configuration, and reconnect."],
  ["Entra changed but tracker uses old configuration","Displayed audience/authority is out of date.","Verified metadata has a short cache; manual fallbacks cannot remotely monitor Entra.","Click Refresh configuration. Reconnect after authority changes. If reading is unavailable, inspect Entra and save the correct manual fallback yourself.","Check fresh validation time and verification label. Verified metadata is cached for at most five minutes."],
  ["Missing backend permission to read signInAudience","Automatic audience detection is unavailable or denied.","No reader, missing Application.Read.All approval, or unrelated/non-allowlisted tenant/app.","For controlled registrations, configure the backend reader and explicit app allowlist. For third-party registrations use automatic sign-in; an explicit account-type override is optional. Never share client secrets or request broad directory permission from ordinary users.","Refresh and look for a fresh Verified label. Mailbox login alone does not verify registration metadata."],
  ["Network loss / uncertain send outcome","The browser cannot tell whether Microsoft accepted the request.","The connection failed after POST or a server response was ambiguous.","Keep the item paused. Check Sent Items before deciding whether to retry. Reconnecting does not prove the previous message was not sent.","Resolve the uncertain outcome deliberately; never resend merely because an error appeared."],
];
